services:
  fourget:
    build: .
    restart: unless-stopped
    environment:
      - FOURGET_PROTO=http
      - FOURGET_SERVER_NAME=4get.ca
      - FOURGET_INSTANCES=https://4get.ca
    ports:
      - "4000:80"
